export const ADD_CORRECT_ANSWER = 'ADD_CORRECT_ANSWER';
export const ADD_WRONG_ANSWER = 'ADD_WRONG_ANSWER';
export const ADD_ACTIVE_SOUND = 'ADD_ACTIVE_SOUND';
export const ADD_ARRAY_OF_WORDS = 'ADD_ARRAY_OF_WORDS';
export const ADD_ARRAY_LENGTH = 'ADD_ARRAY_LENGTH';
export const RETURN_TO_INITIAL_STATE = 'RETURN_TO_INITIAL_STATE';
export const ADD_STAR = 'ADD_STAR';
